platform :ios, '7.1'

target 'MWPhotoBrowser_Example' do

  pod 'ABMediaPlayer', :path => '../../ABMediaPlayer'
  pod 'MWPhotoBrowser', :path => "../"
end

target 'MWPhotoBrowser_Tests' do
  pod 'ABMediaPlayer', :path => '../../ABMediaPlayer'
  pod 'MWPhotoBrowser', :path => "../"

  pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase', '~> 1.8.1'
  pod 'Expecta+Snapshots'
end
